### ISSUE TITLE
Example autocomplete with ajax call

### ISSUE THREAD

**Issue by lucianoreis** [quasarframework/quasar-edge#2]
Where do I see an example call with ajax?
My goal is a similar functionality with jQuery select2.

**Comment by rstoenescu** [comment]
Hi, please use forum for questions. Github tickets are reserved for issues or proposals only. Thanks.

**Comment by shayneoAtNorwood** [comment]
Not sure why that was closed and rebuffed without a commit to fix the problem, its pretty clearly a request for documentation even if phrased as a "wheres the documentation" , as autocomplete pretty much isn't documented (Theres no real way to determine what format the array passed back for an ajax request via done(), based on the documentation. Its just assumed the user can guess it.

**Comment by shayneoAtNorwood** [comment]
Some documentation would help. Theres really no way to determine how to use the autocomplete with ajax, as theres no documentation on what format the data going back through done() works. The natural assumption is a list of strings. Apparently not! As it stands, the feature is undocumentated

**Comment by rstoenescu** [comment]
@shayneoAtNorwood http://quasar-framework.org/components/autocomplete.html
Check the source code of the demo (hit the "View source") if you need more clarifications. That's why it's there...
Will enhance docs if you have trouble with it.
